### ISSUE TITLE
`onTouchEvent` does not handle `MotionEvent.ACTION_POINTER_UP`

### ISSUE THREAD

**Issue by nobuyukishikano** [rhlff/NestedScrollWebView#10]
When I zoom a `WebView` by pinching, zooming will suddenly be canceled.
It seems that `onTouchEvent` does not handle `MotionEvent.ACTION_POINTER_UP`.
I added  `case MotionEvent.ACTION_POINTER_UP` at L109 (or changed L108 - L110 to `default:`),
and it works fine.
Could you confirm this?

**Comment by tobiasrohloff** [comment]
I only used this for WebViews with a fixed viewport, thus zooming was never a supported feature.

**Comment by ahar-zz** [comment]
@nobuyukishikano have you fixed this issue?
