### ISSUE TITLE
Failed to resolve: com.github.rhlff:NestedScrollWebView:v1.0.2

### ISSUE THREAD

**Issue by natanloterio** [rhlff/NestedScrollWebView#14]
Hi there, 

I just started working on this project for a new client and they are using the NestedScrollWebView. 
My gradle can't find your dependency on jitpack. Did you removed it from Jitpack?

project level build.gradle

```
allprojects { 
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        flatDir {
            dirs "../libs"
        }
    }
}

```

app level build.project
`implementation 'com.github.rhlff:NestedScrollWebView:v1.0.2'`

**Comment by QuentinGuillout** [comment]
I have the same problem, but it seems like it is on jitpack ?
[https://jitpack.io/#com.github.rhlff/NestedScrollWebView](https://jitpack.io/#com.github.rhlff/NestedScrollWebView)
I don't understand...

**Comment by natanloterio** [comment]
@QuentinGuillout , just found a solution. But you'll need to import the project as a lib.

Just follow the instructions here 
[https://github.com/tobiasrohloff/NestedScrollWebView/tree/v1.0.2](https://github.com/tobiasrohloff/NestedScrollWebView/tree/v1.0.2)

**Comment by QuentinGuillout** [comment]
I did something similar in the end, I imported it as an android project and created an .aar while waiting for this issue to be fixed. Thanks a lot !

**Comment by tobiasrohloff** [comment]
I just updated the JitPack setup and a couple of dependencies. The build is green again. :) 

Feel free to try version `'com.github.rhlff:NestedScrollWebView:v1.1.1'`.
