### ISSUE TITLE
Unable to import package.

### ISSUE THREAD

**Issue by dadada** [rhlff/NestedScrollWebView#15]
`implementation 'com.github.rhlff:NestedScrollWebView:v1.1.1'` in maven repo definition

vs

`package com.tobiasrohloff.view;` in library.

This way I was unable to import the package after adding the above `implementation` to my dependency list. This worked before cbb0a83702f107788daf3f60abb25a8ba1722bd4

Note that neither `import package com.tobiasrohloff.view;` nor `import com.github.rhlff:NestedScrollWebView`, nor `import com.github.tobiasrohloff.NestedScrollWebView` works.

**Comment by YvesCheung** [comment]
Build artifacts:
com.github.tobiasrohloff:NestedScrollWebView:v1.1.1

Files: 
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1/NestedScrollWebView-v1.1.1-sources.jar
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1/NestedScrollWebView-v1.1.1.pom
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1/NestedScrollWebView-v1.1.1.pom.md5
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1/NestedScrollWebView-v1.1.1.pom.sha1
com/github/tobiasrohloff/NestedScrollWebView/v1.1.1/build.log

Look at your jitpack build log, there have no file named 'NestedScrollWebView-v1.1.1.jar'.
Your publish script is wrong, which is no jar artifect uploaded at all！
