### ISSUE TITLE
Bouncy scrolling in BottomSheetDialogFragment

### ISSUE THREAD

**Issue by LouisCAD** [rhlff/NestedScrollWebView#7]
Hi, I tried using this library in a `BottomSheetDialogFragment`, and it worked pretty well, apart from the bouncy scrolling when settling the BottomSheet by dragging the finger. Does anyone have an idea of the cause of this issue? Also, sometimes, the WebView scrolls up while dragging the bottom sheet from expanded to peek state.

**Comment by tobiasrohloff** [comment]
Hi,

this library is mainly tested with the regular `ToolbarLayout`, all other layouts are out of scope for us at the moment. But I'm happy to review any PR.

**Comment by fm-sys** [comment]
I found the following gist, which is working perfectly fine:

https://gist.github.com/alexmiragall/0c4c7163f7a17938518ce9794c4a5236
