### ISSUE TITLE
[suggestion] use delight-im/Android-AdvancedWebView instead of just WebView

### ISSUE THREAD

**Issue by kasim1011** [rhlff/NestedScrollWebView#9]
Use [`Android-AdvancedWebView`](https://github.com/delight-im/Android-AdvancedWebView) for `Cookie` support and other basic features.

**Comment by tobiasrohloff** [comment]
This is just a small wrapper around the regular `WebView`. If you would like to see a similar implementation for your `WebView` replacement, please open a ticket there that this class should implement `NestedScrollingChild` as well. I will not switch to this large dependency. This lib should be as lightweight as possible.

**Comment by kasim1011** [comment]
@tobiasrohloff 

Thanks for suggestion.
